"""Configuration module for XMPP bot."""

from .constants import (
    DEFAULT_CONNECT_TIMEOUT,
    DEFAULT_DEBUG,
    DEFAULT_KEEPALIVE_INTERVAL,
    DEFAULT_RESOURCE,
    DEFAULT_RETRY_DELAY,
    DEFAULT_SEND_DELAY,
    MESSAGE_CHAT,
    MESSAGE_GROUPCHAT,
    MESSAGE_NORMAL,
    PRESENCE_AVAILABLE,
    PRESENCE_SUBSCRIBE,
    PRESENCE_SUBSCRIBED,
    PRESENCE_UNAVAILABLE,
    PRESENCE_UNSUBSCRIBE,
    PRESENCE_UNSUBSCRIBED,
)
from .settings import Settings

__all__ = [
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_DEBUG",
    "DEFAULT_KEEPALIVE_INTERVAL",
    "DEFAULT_RESOURCE",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_SEND_DELAY",
    "MESSAGE_CHAT",
    "MESSAGE_GROUPCHAT",
    "MESSAGE_NORMAL",
    "PRESENCE_AVAILABLE",
    "PRESENCE_SUBSCRIBE",
    "PRESENCE_SUBSCRIBED",
    "PRESENCE_UNAVAILABLE",
    "PRESENCE_UNSUBSCRIBE",
    "PRESENCE_UNSUBSCRIBED",
    "Settings",
]
